insert into joke (text, author)
values ('Why was the math teacher late to work? She took the rhombus.', 'unknown'),
       ('Im really excited for the next autopsy club. Its open Mike night!', 'unknown'),
       ('Where do spiders seek health advice? WebMD.', 'unknown'),
       ('What did Yoda say when he saw himself in 4K? "HDMI."', 'unknown'),
       ('My daughter thinks I dont give her enough privacy. At least thats what she wrote in her diary.', 'unknown'),
       ('A friend of mine got into photographing salmon in different clothing. He said he liked shooting fish in apparel.', 'unknown'),
       ('Why cant you trust an atom? Because they make up everything.', 'unknown'),
       ('Id like to go to Holland someday. Wooden shoe?', 'unknown'),
       ('The guy that invented the umbrella was gonna call it the brella. But he hesitated.', 'unknown'),
       ('Fun fact: Australias biggest export is boomerangs. Its also their biggest import.', 'unknown'),
       ('What kind of car runs on leaves? An autumn-mobile!', 'unknown'),
       ('I tried to organize a professional Hide-and-Seek tournament, but it was a complete failure. Good players are hard to find.', 'unknown'),
       ('Before the invention of the wheel… everything was a drag!', 'unknown'),
       ('What do you call it when Dwayne Johnson buys a cutting tool? Rock pay-for scissors.', 'unknown'),
       ('What do you call a hippies wife? A Mississippi!', 'unknown'),
       ('What did the duck say when she bought a lipstick? Put it on my bill!', 'unknown'),
       ('What do you call a man with a rubber toe? Roberto!', 'unknown'),
       ('What do you give to a sick lemon? Lemon aid!', 'unknown'),
       ('What did the little mountain say to the bigger mountain? Hi Cliff!', 'unknown'),
       ('Why are there gates around cemeteries? Because people are dying to get in!', 'unknown'),
       ('What do you call a cow with two legs? Lean beef!', 'unknown'),
       ('What do bees do if they need a ride? Wait at the buzz stop!', 'unknown'),
       ('What do you call a monkey that loves Doritos? A chipmunk!', 'unknown'),
       ('Why did the can crusher quit his job? Because it was soda pressing!', 'unknown'),
       ('Do you remember that joke I told you about my spine? It was about a weak back!', 'unknown'),
       ('I just went to an emotional wedding. Even the cake was in tiers.', 'unknown'),
       ('Whens the best time to go to the dentist? Tooth-hurtie!', 'unknown'),
       ('Why do seagulls fly over the sea? Because if they flew over the bay, theyre bagels!', 'unknown'),
       ('What do you call a farm that makes bad jokes? Corny!', 'unknown'),
       ('Why do fish live in salt water? Because pepper makes them sneeze!', 'unknown'),
       ('What kind of streets do ghosts haunt? Dead ends!', 'unknown'),
       ('What do you tell actors to break a leg? Because every play has a cast!', 'unknown'),
       ('What kind of dogs love car racing? Lap dogs!', 'unknown'),
       ('What did Winnie the Pooh say to his agent? "Show me the honey!"', 'unknown'),
       ('What do you call birds who stick together? Vel-crows.', 'unknown'),
       ('Today I gave my dead batteries away. They were free of charge.', 'unknown'),
       ('What do you call it when one cow spies on another? A steak out!', 'unknown'),
       ('What happens when a frogs car breaks down? It gets toad!', 'unknown'),
       ('Whats the best thing about Switzerland? I dont know, but its flag is a big plus!', 'unknown'),
       ('My favorite word is "drool." It just rolls off the tongue.', 'unknown'),
       ('Why is Peter Pan always flying? He neverlands.', 'unknown'),
       ('I just wrote a book on reverse psychology. Do not read it.', 'unknown'),
       ('What does a zombie vegetarian eat? "Graaaaaaaains!"', 'unknown'),
       ('My new thesaurus is terrible. Not only that, its also terrible.', 'unknown'),
       ('What did the blanket say as it fell off the bed? "Oh sheet!"', 'unknown'),
       ('Why do cow-milking stools only have three legs? Cause the cows got the udder!', 'unknown'),
       ('How did Darth Vader know what Luke got him for Christmas? He felt his presents.', 'unknown'),
       ('Whats the last thing that goes through a bugs mind when it hits a windshield? Its butt.', 'unknown'),
       ('What did the janitor say when he jumped out of the closet? "Supplies!"', 'unknown'),
       ('Imagine if Americans switched from pounds to kilograms overnight. There would be mass confusion!', 'unknown'),
       ('Its inappropriate to make a "dad joke" if you are not a dad. Its a faux pa.', 'unknown'),
       ('What did Batman say to Robin before they got in the car? "Robin, get in the car."', 'unknown'),
       ('I have an addiction to cheddar cheese. But its only mild.', 'unknown'),
       ('Why shouldnt you write with a broken pencil? Because its pointless!', 'unknown'),
       ('Why did the scarecrow win an award? He was outstanding in his field.', 'unknown'),
       ('What did the buffalo say when his son left? Bison!', 'unknown'),
       ('I was sitting in traffic the other day.  Probably why I got run over.', 'unknown'),
       ('Whats red and shaped like a bucket? A blue bucket painted red.', 'unknown'),
       ('What dont ants get sick? They have anty-bodies.', 'unknown'),
       ('What do you call a fish with no eye? Fsh.', 'unknown'),
       ('Why do you smear peanut butter on the road? To go with the traffic jam.', 'unknown'),
       ('When is your door not actually a door? When its ajar.', 'unknown'),
       ('Whats green, fuzzy, and would hurt if it fell on you out of a tree? A pool table.', 'unknown'),
       ('A communist joke isnt funny unless everyone gets it.', 'unknown'),
       ('What did one dish say to the other? Dinner is on me!', 'unknown'),
       ('What does a house wear? Address!', 'unknown'),
       ('Why cant you hear a Pterodactyl go to the bathroom? Because the pee is silent.', 'unknown'),
       ('Cosmetic surgery used to be such a taboo subject. Now you can talk about Botox and nobody raises an eyebrow.', 'unknown'),
       ('What do you call someone who immigrated to Sweden? Artificial Swedener.', 'unknown'),
       ('Have you heard the one about the corduroy pillow? Its making headlines.', 'unknown'),
       ('Whats the dumbest animal in the jungle? A polar bear!', 'unknown'),
       ('Im thinking about removing my spine. I feel like its only holding me back.', 'unknown'),
       ('Did you hear about the two thieves who stole a calendar? They each got six months.', 'unknown'),
       ('Im terrified of elevators so Im going to start taking steps to avoid them.', 'unknown'),
       ('Have you heard of the band 923 Megabytes? Probably not, they havent had a gig yet.', 'unknown');